import Head from 'next/head'
import Hero from '@/components/Hero'
import Quote from '@/components/Quote'
import Projects from '@/components/Projects'
import Skills from '@/components/Skills'
import About from '../components/About'
import Contact from '@/components/Contact'

export default function Home() {
  return (
    <>
      <Head>
        <title>Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-dark font-fira overflow-hidden'>
      
      <Hero/>
     <Quote/>
     <Projects/>
     <Skills/>
      <About/>
      <Contact/>
      </main>
    </>
  )
}
